AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DemoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Demo Security Group

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  DemoInstance:
    Type: AWS::EC2::Instance

    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f58b397bc5c1f2e8
